AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Naming/PredicateName:
  Enabled: false
