# frozen_string_literal: true

require "active_record"
require "fx"
require_relative "hoardable/version"
require_relative "hoardable/arel_visitors"
require_relative "hoardable/schema_statements"
require_relative "hoardable/engine"
require_relative "hoardable/finder_methods"
require_relative "hoardable/scopes"
require_relative "hoardable/error"
require_relative "hoardable/database_client"
require_relative "hoardable/source_model"
require_relative "hoardable/version_model"
require_relative "hoardable/model"
require_relative "hoardable/associations"
require_relative "hoardable/has_many"
require_relative "hoardable/belongs_to"
require_relative "hoardable/has_one"
require_relative "hoardable/has_rich_text"
require_relative "generators/hoardable/migration_generator"
require_relative "generators/hoardable/install_generator"
